"""
Situation Primitives Catalog — auto-generated from YAML cards.

Total: 39 situations across 6 categories.

DO NOT EDIT MANUALLY. Regenerate with: python scripts/compile_situations.py
"""


SITUATIONS = {
    "abundance-asymmetry": {
        "name": "Abundance Asymmetry",
        "category": "resource-pressure",
        "essence": "Some have more than enough while others have nothing — the gap itself is the pressure",
        "psychological_pressure": "Inequality demands a story. The haves need to believe they deserve it. The have-nots need to believe it can change. When neither story holds, the pressure becomes unbearable.",
        "shadow_trigger": "The wealthy become defensive or guilty. The poor become resentful or self-blaming. Both sides lose the ability to see the other as fully human.",
        "observable_markers": [
            "Visible inequality that cannot be ignored or explained away",
            "Those with abundance must justify having or sharing",
            "Those without must decide between acceptance, appeal, or taking",
        ],
        "pressure_targets": [
            {"primitive_id": "generosity", "activation": "Giving is easy when you have plenty. But how much? And does giving fix the underlying imbalance?"},
            {"primitive_id": "justice-seeking", "activation": "The inequality itself may be the injustice. Charity treats symptoms; justice demands structural change."},
            {"primitive_id": "defiance-rebellion", "activation": "Those with less may see the system as rigged and resist it."},
            {"primitive_id": "guilt-conscience", "activation": "Those with more may feel undeserved guilt — or suppress it through rationalization."},
            {"primitive_id": "envy", "activation": "Awareness of what others have intensifies desire for what you lack."},
        ],
        "shadow_activators": ["envy", "guilt-conscience", "pride"],
        "intensity": "moderate",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["power-imbalance", "means-vs-ends"],
        "tension_situations": ["resource-scarcity"],
    },
    "authority-under-question": {
        "name": "Authority Under Question",
        "category": "power-dynamics",
        "essence": "Someone's right to lead, decide, or command is being challenged — legitimacy itself is on trial",
        "psychological_pressure": "For the leader: if authority must be justified, it is already weakened. For the challenger: questioning authority risks everything if the challenge fails.",
        "shadow_trigger": "The leader becomes authoritarian to suppress doubt. The challenger becomes destructive, tearing down without building alternatives.",
        "observable_markers": [
            "Subordinates questioning decisions rather than following them",
            "The leader defending their position rather than exercising it",
            "Competing claims to authority emerging from the group",
        ],
        "pressure_targets": [
            {"primitive_id": "charismatic-leadership", "activation": "Leadership through inspiration is tested — can you lead people who doubt you?"},
            {"primitive_id": "defiance-rebellion", "activation": "The instinct to resist authority finds its moment. But rebellion without alternative is chaos."},
            {"primitive_id": "pride", "activation": "The leader's identity is fused with their authority. Losing it means losing self."},
            {"primitive_id": "duty-over-desire", "activation": "Is stepping down the responsible choice, or is holding firm the duty?"},
            {"primitive_id": "truth-above-all", "activation": "The honest assessment of whether the leader deserves authority may be the hardest truth to speak — or hear."},
        ],
        "shadow_activators": ["pride", "wrath", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["contested-resource", "power-imbalance"],
        "tension_situations": ["forced-alliance"],
    },
    "baptism-of-fire": {
        "name": "Baptism of Fire",
        "category": "identity-threat",
        "essence": "Your first real fight — the moment violence stops being abstract and becomes the thing you survived",
        "psychological_pressure": "You imagined how you would be in a fight. You were wrong. The person who walked into that battle is not the person who walked out. The question now is which version of you is real.",
        "shadow_trigger": "Violence becomes addictive — the intensity of combat replaces all other feeling. Or violence becomes paralyzing — the memory freezes the body whenever danger approaches.",
        "observable_markers": [
            "The thousand-yard stare after a first battle",
            "Obsessive retelling of the moment — trying to make it make sense",
            "A permanent before-and-after division in the character's timeline",
        ],
        "pressure_targets": [
            {"primitive_id": "survival-instinct", "activation": "The body's refusal to die — activated fully for the first time. The discovery that you will fight to live even when your mind has frozen."},
            {"primitive_id": "risk-taking", "activation": "Relationship with risk is permanently recalibrated. Some become fearless; others become paralyzed. Neither response is chosen."},
            {"primitive_id": "self-mastery", "activation": "Could you control yourself? Did you freeze, flee, or fight? The answer defines your self-image going forward."},
            {"primitive_id": "capacity-for-change", "activation": "You are different now. The pre-battle self is gone. The question is whether you can integrate the new self or whether it remains alien."},
            {"primitive_id": "rage-response", "activation": "The discovery of your own capacity for violence — the moment you realized you could kill, and the question of what that makes you."},
        ],
        "shadow_activators": ["wrath", "fragmentation", "pride"],
        "intensity": "extreme",
        "escalation_pattern": "acute",
        "complementary_situations": ["the-ordeal", "loss-of-kin"],
        "tension_situations": ["the-return"],
    },
    "betrayal-discovery": {
        "name": "Betrayal Discovery",
        "category": "relational-tension",
        "essence": "Someone you trusted has deceived you — the relationship was not what you believed",
        "psychological_pressure": "Betrayal doesn't just damage the relationship — it damages the self that trusted. 'I should have known' becomes 'I'm a fool for believing.' The wound is retrospective — it rewrites history.",
        "shadow_trigger": "Generalized mistrust. One betrayal becomes proof that no one can be trusted. The betrayed becomes the one who preemptively betrays to avoid being vulnerable again.",
        "observable_markers": [
            "Re-reading past interactions through the lens of betrayal",
            "Oscillation between denial, rage, and grief",
            "Trust in all relationships contaminated by the specific betrayal",
            "Replaying every conversation, searching for the lies hidden in kindness",
            "The sick realization that loyalty was a one-way street",
        ],
        "pressure_targets": [
            {"primitive_id": "loyal-companionship", "activation": "Loyalty was given and exploited. The most loyal are the most damaged because they invested the most trust."},
            {"primitive_id": "rage-response", "activation": "Betrayal is one of the most reliable triggers for explosive anger. The fury is proportional to the trust that was broken."},
            {"primitive_id": "isolation-as-protection", "activation": "If trust leads to betrayal, the logical conclusion is to trust no one. Withdrawal becomes self-preservation."},
            {"primitive_id": "connection-seeking", "activation": "The need for connection doesn't disappear — but the mechanism for achieving it is broken."},
            {"primitive_id": "truth-above-all", "activation": "The betrayal was a lie. Truth-seekers want to understand: what was real and what was performance?"},
        ],
        "shadow_activators": ["wrath", "fragmentation", "pride"],
        "intensity": "extreme",
        "escalation_pattern": "acute",
        "complementary_situations": ["exposed-secret", "information-asymmetry"],
        "tension_situations": ["forced-alliance"],
    },
    "born-out-of-place": {
        "name": "Born Out of Place",
        "category": "identity-threat",
        "essence": "You were born into the wrong world — noble blood in common soil, or common blood in a gilded cage",
        "psychological_pressure": "You always knew something was wrong — you didn't fit, and you couldn't explain why. The revelation of your true origins doesn't fix the displacement. Now you don't belong in either world.",
        "shadow_trigger": "Entitlement. The discovery of higher birth becomes license to despise the world that raised you. Or rejection — refusing the true origins because the false ones are all you know.",
        "observable_markers": [
            "A persistent sense of not belonging that predates any specific event",
            "Skills, instincts, or sensibilities that don't match the environment",
            "Discovery of true origins that explains the lifelong sense of displacement",
        ],
        "pressure_targets": [
            {"primitive_id": "inherited-identity", "activation": "The central tension — identity was inherited from the wrong source. Now two lineages compete for the same self."},
            {"primitive_id": "belonging-seeking", "activation": "Neither world fully accepts you. The common folk see something foreign; the nobles see something common. Belonging is always partial."},
            {"primitive_id": "defiance-rebellion", "activation": "Rejecting both worlds — refusing to be defined by either lineage. The rebellion is against the idea that birth determines worth."},
            {"primitive_id": "pride", "activation": "True origins may be higher or lower than assumed. Either direction wounds pride — discovering you're 'above' your raising or 'below' your expectations."},
            {"primitive_id": "adaptive-flexibility", "activation": "Survival between worlds requires fluency in both. The displaced person becomes a translator, a bridge — or a spy in both camps."},
        ],
        "shadow_activators": ["pride", "envy", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["exile-banishment", "reputation-under-attack"],
        "tension_situations": ["forced-role-change"],
    },
    "coerced-compliance": {
        "name": "Coerced Compliance",
        "category": "power-dynamics",
        "essence": "You must do something against your will — the alternative is worse than compliance",
        "psychological_pressure": "Compliance without consent is a specific kind of violence to the self. You act against your values, and the acting makes it feel like your choice even though it wasn't.",
        "shadow_trigger": "The coerced begin to identify with the coercer — compliance becomes internalized as agreement. The coercer convinces themselves that obedience equals consent.",
        "observable_markers": [
            "Compliance accompanied by visible distress or suppressed anger",
            "The coercer framing the demand as reasonable or inevitable",
            "Internal resistance that cannot be expressed externally",
        ],
        "pressure_targets": [
            {"primitive_id": "defiance-rebellion", "activation": "Every fiber says resist. But resistance may be suicidal. The tension between refusal and survival is excruciating."},
            {"primitive_id": "stoic-acceptance", "activation": "Endurance as strategy — comply now, resist later. But when does 'later' come?"},
            {"primitive_id": "rage-response", "activation": "Anger with no safe outlet turns inward. Suppressed fury corrodes from within."},
            {"primitive_id": "self-mastery", "activation": "Discipline is tested at its extreme — maintaining inner autonomy while outer behavior is controlled."},
            {"primitive_id": "adaptive-flexibility", "activation": "Survival may require becoming someone you don't recognize. Adaptation has a limit where it becomes surrender."},
        ],
        "shadow_activators": ["wrath", "fragmentation", "resistance-to-change"],
        "intensity": "extreme",
        "escalation_pattern": "acute",
        "complementary_situations": ["power-imbalance", "means-vs-ends"],
        "tension_situations": ["authority-under-question"],
    },
    "contested-resource": {
        "name": "Contested Resource",
        "category": "resource-pressure",
        "essence": "Multiple parties claim the same thing — ownership, control, or access is disputed",
        "psychological_pressure": "The resource is a proxy for deeper conflicts — status, justice, identity. Losing the contest means more than losing the thing itself.",
        "shadow_trigger": "Winning becomes identity. The resource matters less than not losing. Compromise feels like surrender.",
        "observable_markers": [
            "Competing claims backed by different logics (precedent, need, power, right)",
            "Negotiation, posturing, or threats over access",
            "Third parties pressured to take sides",
        ],
        "pressure_targets": [
            {"primitive_id": "justice-seeking", "activation": "Each side believes their claim is fair. Justice-seeking must navigate competing legitimate claims."},
            {"primitive_id": "defiance-rebellion", "activation": "If the current holder has power, challengers must decide whether to accept or resist."},
            {"primitive_id": "strategic-deception", "activation": "Information about the resource's true value or one's own needs becomes leverage."},
            {"primitive_id": "harmony-over-conflict", "activation": "The peacemaker is torn — compromise may satisfy no one fully."},
            {"primitive_id": "pride", "activation": "Conceding ground feels like losing face. The contest becomes personal."},
        ],
        "shadow_activators": ["wrath", "envy", "pride"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["resource-scarcity", "power-imbalance", "authority-under-question"],
        "tension_situations": ["sacrifice-demanded"],
    },
    "countdown-crisis": {
        "name": "Countdown Crisis",
        "category": "temporal-pressure",
        "essence": "Time is running out — the window for action is closing and the cost of delay is catastrophic",
        "psychological_pressure": "The clock compresses every decision. There's no time to be right — only time to be fast. Mistakes become permanent because there's no time to correct them.",
        "shadow_trigger": "Urgency justifies anything. Process, consultation, ethics — all abandoned in the name of speed. Whoever acts fastest claims authority regardless of wisdom.",
        "observable_markers": [
            "Decision-making accelerates, deliberation contracts",
            "Perfectionism gives way to 'good enough'",
            "People who normally think become people who act",
        ],
        "pressure_targets": [
            {"primitive_id": "impulsive-action", "activation": "Finally validated — the situation demands action without deliberation. But impulsivity doesn't distinguish between speed and recklessness."},
            {"primitive_id": "methodical-approach", "activation": "There is no time for steps, stages, or systematic analysis. The methodical mind must abandon its process or be left behind."},
            {"primitive_id": "anxious-vigilance", "activation": "Every worst case is now immediate. Vigilance spikes but there's no time to act on what's noticed."},
            {"primitive_id": "patient-observation", "activation": "Patience is a luxury. Observation without action becomes paralysis."},
            {"primitive_id": "charismatic-leadership", "activation": "Someone must decide NOW. The one who decides becomes the leader regardless of title."},
        ],
        "shadow_activators": ["fragmentation", "wrath", "pride"],
        "intensity": "extreme",
        "escalation_pattern": "acute",
        "complementary_situations": ["resource-scarcity", "individual-vs-collective"],
        "tension_situations": ["prolonged-uncertainty"],
    },
    "debt-called-due": {
        "name": "Debt Called Due",
        "category": "relational-tension",
        "essence": "A past obligation comes due — what was promised must now be paid, and the cost has changed since the bargain was struck",
        "psychological_pressure": "You agreed. Maybe you were desperate, maybe you were naive, maybe the terms seemed fair then. They don't now. But the agreement exists, and the creditor is here. Honour says pay. Survival says refuse. Justice is unclear on which side it stands.",
        "shadow_trigger": "The creditor becomes predatory — the debt was always the point, not the original exchange. Or the debtor becomes self-righteous — rewriting history to make the bargain something that was done TO them rather than something they agreed to.",
        "observable_markers": [
            "The debtor arguing that circumstances have changed, the terms were unfair, they didn't understand",
            "The creditor insisting on the letter of the agreement",
            "Third parties drawn in — was the bargain just? Does it matter?",
        ],
        "pressure_targets": [
            {"primitive_id": "duty-over-desire", "activation": "Duty says honour the agreement. Desire says the cost is too high. The primitive is caught between the obligation that was and the reality that is."},
            {"primitive_id": "strategic-deception", "activation": "The temptation to reframe, redefine, or escape the terms. Lawyers, loopholes, and selective memory become tools."},
            {"primitive_id": "justice-seeking", "activation": "Was the bargain fair? Does fairness at the time of the deal matter more than fairness at the time of payment? Justice-seeking must navigate two legitimate frameworks."},
            {"primitive_id": "rage-response", "activation": "Fury at being held to terms that feel exploitative — whether the original bargain was exploitative or not."},
            {"primitive_id": "humility", "activation": "Accepting that you owe what you owe. Not because the system is fair, but because you gave your word. Humility as the willingness to pay."},
        ],
        "shadow_activators": ["wrath", "pride", "guilt-conscience"],
        "intensity": "high",
        "escalation_pattern": "acute",
        "complementary_situations": ["power-imbalance", "means-vs-ends", "coerced-compliance"],
        "tension_situations": ["forced-alliance"],
    },
    "divine-calling": {
        "name": "Divine Calling",
        "category": "moral-dilemma",
        "essence": "A power beyond mortal understanding has chosen you — the weight of purpose you did not ask for",
        "psychological_pressure": "If the calling is real, refusing it is the greatest sin. If it's delusion, following it is madness. There is no test that resolves the question. You must act on faith or refuse on doubt — and both carry infinite stakes.",
        "shadow_trigger": "The divine calling becomes divine entitlement. The chosen one stops listening to humans because they answer only to God. Certainty becomes tyranny.",
        "observable_markers": [
            "Claims of visions, voices, or undeniable signs that others cannot verify",
            "Willingness to endure suffering that makes no sense without the divine context",
            "The isolation of certainty — knowing something no one else believes",
        ],
        "pressure_targets": [
            {"primitive_id": "faith-driven-purpose", "activation": "The central primitive — divine mandate activated at full intensity. Everything else bends around this calling."},
            {"primitive_id": "duty-over-desire", "activation": "The calling demands things the person would never choose. Duty to God overrides duty to self, and the cost is measured in everything human."},
            {"primitive_id": "humility", "activation": "True calling requires humility — the vessel is not the message. But the certainty of being chosen can destroy humility entirely."},
            {"primitive_id": "truth-above-all", "activation": "Is the calling true? The most honest person must interrogate their own experience — is this God or is this madness?"},
            {"primitive_id": "defiance-rebellion", "activation": "Refusing the call. Wrestling with God, as Jacob did. The right to say no to the divine — if such a right exists."},
        ],
        "shadow_activators": ["pride", "fragmentation", "guilt-conscience"],
        "intensity": "extreme",
        "escalation_pattern": "building",
        "complementary_situations": ["sacred-guardianship", "the-ordeal"],
        "tension_situations": ["forbidden-knowledge"],
    },
    "exile-banishment": {
        "name": "Exile and Banishment",
        "category": "identity-threat",
        "essence": "You have been cast out — removed from the place, people, and identity that defined you",
        "psychological_pressure": "Exile severs the connection between self and place. You are who you were — but only in your own mind. To everyone in the new place, you are no one. To everyone in the old place, you are a memory. The exile exists in neither world fully.",
        "shadow_trigger": "Exile as identity. The banished person becomes nothing but their banishment — every thought oriented toward return, every present moment denied in favor of the past. Or total assimilation — killing the old self to survive in the new world.",
        "observable_markers": [
            "The exiled carrying tokens of what they lost",
            "Oscillation between plans to return and acceptance of permanent displacement",
            "Identity defined increasingly by what was taken rather than what remains",
        ],
        "pressure_targets": [
            {"primitive_id": "belonging-seeking", "activation": "The fundamental need — denied. Belonging is not just wanting community; it's needing a place where your existence makes sense."},
            {"primitive_id": "defiance-rebellion", "activation": "Rage at the sentence. Whether the exile was just or unjust, the instinct to resist, to refuse the verdict, to fight back."},
            {"primitive_id": "stoic-acceptance", "activation": "Ovid in Tomis. Dante in Ravenna. The exile who endures without bitterness destroys nothing — but the endurance itself is a kind of slow death."},
            {"primitive_id": "melancholic-tendency", "activation": "Saudade, hiraeth, toska — every language has a word for the exile's grief because every culture has known exile."},
            {"primitive_id": "adaptive-flexibility", "activation": "Survival in a new place requires becoming someone new. But how much can you change before you've lost the thing you were exiled for being?"},
        ],
        "shadow_activators": ["wrath", "envy", "pride"],
        "intensity": "high",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["forced-role-change", "the-outsider-arrives", "reputation-under-attack"],
        "tension_situations": ["the-return"],
    },
    "exposed-secret": {
        "name": "Exposed Secret",
        "category": "identity-threat",
        "essence": "Something hidden is now known — the private self is suddenly public",
        "psychological_pressure": "The gap between the performed self and the actual self has collapsed. Everyone who knew you before now knows something you chose to hide. You can't un-ring the bell.",
        "shadow_trigger": "Denial escalating into aggression — attacking those who know the secret. Or total collapse — the secret was load-bearing, and without it the identity structure fails.",
        "observable_markers": [
            "Attempts to control the narrative after the revelation",
            "Others re-evaluating the exposed person in light of new information",
            "The exposed person oscillating between defiance and shame",
        ],
        "pressure_targets": [
            {"primitive_id": "strategic-deception", "activation": "The deception has failed. Damage control is itself another layer of deception — or the moment to abandon deception entirely."},
            {"primitive_id": "truth-above-all", "activation": "The truth is out, but not on your terms. For truth-seekers, this may be relief or violation depending on context."},
            {"primitive_id": "isolation-as-protection", "activation": "The instinct to withdraw is overwhelming. If you can't control what they know, control who has access."},
            {"primitive_id": "pride", "activation": "Shame is pride's shadow. The exposure attacks self-image at its foundation."},
            {"primitive_id": "humor-as-defense", "activation": "Making light of the revelation — if you laugh first, you control the narrative."},
        ],
        "shadow_activators": ["pride", "fragmentation", "wrath"],
        "intensity": "high",
        "escalation_pattern": "acute",
        "complementary_situations": ["loyalty-vs-truth", "reputation-under-attack"],
        "tension_situations": ["information-asymmetry"],
    },
    "forbidden-connection": {
        "name": "Forbidden Connection",
        "category": "relational-tension",
        "essence": "Two people are drawn together despite a structural barrier that makes the connection dangerous, shameful, or impossible",
        "psychological_pressure": "The heart doesn't consult the rules. The connection is real — as real as the barrier. You can honour one or the other, but not both. Every moment together is stolen, and every stolen moment makes the next one harder to refuse.",
        "shadow_trigger": "The forbidden becomes the entire identity. The lovers define themselves only by their transgression. Or the connection is abandoned — and the obedient, rule-following self that remains is hollow, living a life that was chosen for it.",
        "observable_markers": [
            "Secret meetings, coded communication, shared glances in public",
            "Both parties oscillating between the pull of connection and the weight of consequence",
            "The world around them organizing to prevent what's already happening",
        ],
        "pressure_targets": [
            {"primitive_id": "connection-seeking", "activation": "The fundamental drive — toward another person, with full knowledge of the cost. Connection-seeking against every practical calculation."},
            {"primitive_id": "loyal-companionship", "activation": "Loyalty to the relationship vs. loyalty to community, family, or law. The forbidden connection demands choosing which loyalty is primary."},
            {"primitive_id": "defiance-rebellion", "activation": "The connection itself is an act of rebellion. Choosing it means choosing against the structure that forbids it."},
            {"primitive_id": "risk-taking", "activation": "Every meeting is a risk. Discovery means punishment — social, physical, spiritual. The risk is not abstract; it's in every glance."},
            {"primitive_id": "isolation-as-protection", "activation": "The connection must be hidden. Secrecy creates a world of two — intimate and suffocating simultaneously."},
        ],
        "shadow_activators": ["guilt-conscience", "pride", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["loyalty-vs-truth", "exposed-secret", "individual-vs-collective"],
        "tension_situations": ["forced-alliance"],
    },
    "forbidden-knowledge": {
        "name": "Forbidden Knowledge",
        "category": "moral-dilemma",
        "essence": "Something you shouldn't know is within reach — and the pull toward it is almost irresistible",
        "psychological_pressure": "Curiosity is not a choice — it's a drive. The forbidden is magnetic precisely because it's forbidden. Every barrier increases the desire. The question isn't whether you want to know — it's whether you can bear not to.",
        "shadow_trigger": "Knowledge without wisdom. The discovery destroys the discoverer because they weren't ready for what they found. Or worse: they were ready, and it changed them into something they didn't want to become.",
        "observable_markers": [
            "Warnings ignored or rationalized away",
            "The forbidden thing described as 'just looking' or 'just understanding'",
            "Others who already know trying to prevent or enable the discovery",
        ],
        "pressure_targets": [
            {"primitive_id": "curiosity-driven-exploration", "activation": "The core drive — the need to know is overwhelming. Curiosity doesn't care about consequences; it cares about the gap between what's known and what isn't."},
            {"primitive_id": "risk-taking", "activation": "The transgression itself is the risk. Reaching for forbidden knowledge means crossing a line that can't be uncrossed."},
            {"primitive_id": "strategic-deception", "activation": "Hiding the pursuit. If others would stop you, you must deceive them. The search for knowledge becomes secret."},
            {"primitive_id": "guilt-conscience", "activation": "You know you shouldn't. The conscience speaks before the hand reaches. Whether you listen is the test."},
            {"primitive_id": "truth-above-all", "activation": "But is the truth itself ever forbidden? The truth-seeker must decide whether truth has limits — and whether those limits are protective or oppressive."},
        ],
        "shadow_activators": ["pride", "guilt-conscience", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["information-asymmetry", "sacred-guardianship", "exposed-secret"],
        "tension_situations": ["prolonged-uncertainty"],
    },
    "forced-alliance": {
        "name": "Forced Alliance",
        "category": "relational-tension",
        "essence": "You must cooperate with someone you oppose — the shared threat is greater than your mutual hostility",
        "psychological_pressure": "Working alongside your enemy requires suppressing everything that makes you enemies. The cooperation is real but the trust is not. Every shared victory feels wrong.",
        "shadow_trigger": "The alliance becomes genuine — and that's terrifying, because it undermines the certainty that the other side is wrong. Or the alliance is sabotaged from within because winning together is worse than losing separately.",
        "observable_markers": [
            "Stiff, formal cooperation with undercurrents of resentment",
            "Credit and blame become contested territory",
            "Both parties watching for betrayal while depending on each other",
        ],
        "pressure_targets": [
            {"primitive_id": "harmony-over-conflict", "activation": "The peacemaker's moment — but the harmony required is with someone you have real reasons to oppose."},
            {"primitive_id": "defiance-rebellion", "activation": "Cooperation feels like surrender. Working with the enemy looks like joining them."},
            {"primitive_id": "strategic-deception", "activation": "How much do you share with your forced ally? The cooperation may itself be strategic — genuine enough to work, calculated enough to protect."},
            {"primitive_id": "adaptive-flexibility", "activation": "Survival demands adaptation. Can you work with this person without becoming like them?"},
            {"primitive_id": "pride", "activation": "Needing your enemy's help is humiliating. Accepting it requires swallowing something fundamental."},
        ],
        "shadow_activators": ["pride", "wrath", "envy"],
        "intensity": "high",
        "escalation_pattern": "cyclical",
        "complementary_situations": ["power-imbalance", "contested-resource"],
        "tension_situations": ["betrayal-discovery", "authority-under-question"],
    },
    "forced-role-change": {
        "name": "Forced Role Change",
        "category": "identity-threat",
        "essence": "You must become someone you're not — circumstances demand a self you haven't built",
        "psychological_pressure": "Identity is not just who you are — it's how you navigate the world. Lose the role, lose the map. The new role may not fit, but the old one is gone.",
        "shadow_trigger": "Clinging to the old role when it no longer serves, or collapsing entirely into the new one without integration. The transition itself is where identity fractures.",
        "observable_markers": [
            "Performing competence in an unfamiliar role",
            "Grief for the identity being left behind",
            "Others treating you as the role rather than the person",
        ],
        "pressure_targets": [
            {"primitive_id": "adaptive-flexibility", "activation": "The core demand — can you become what's needed? Flexibility is tested beyond preference into necessity."},
            {"primitive_id": "resistance-to-change", "activation": "Everything in you says 'this is not who I am.' The resistance is identity defending itself."},
            {"primitive_id": "capacity-for-change", "activation": "Growth requires letting go. But letting go of identity feels like dying."},
            {"primitive_id": "rigid-adherence", "activation": "Principles that defined the old role may obstruct the new one. What do you keep?"},
            {"primitive_id": "isolation-as-protection", "activation": "Withdrawal during transition — the space between roles is lonely because no one recognizes you."},
        ],
        "shadow_activators": ["fragmentation", "resistance-to-change", "pride"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["reputation-under-attack", "individual-vs-collective"],
        "tension_situations": ["prolonged-uncertainty"],
    },
    "griefs-long-shadow": {
        "name": "Grief's Long Shadow",
        "category": "identity-threat",
        "essence": "Someone has died and the death has reorganized who you are — grief not as event but as architecture",
        "psychological_pressure": "The death was long ago. Everyone says you should have moved on. But the dead built rooms in your mind and they still live there. Moving on would mean demolishing the last place they exist.",
        "shadow_trigger": "Grief becomes the organizing principle of identity. The mourner defines themselves by what was lost rather than what remains. New love feels like infidelity to the dead.",
        "observable_markers": [
            "Decades-old habits maintained in honor of the dead — rituals that have outlived their origin",
            "New relationships unconsciously shaped by the template of the lost one",
            "A hollowness in celebration — joy is real but incomplete, forever missing one voice",
        ],
        "pressure_targets": [
            {"primitive_id": "grief-processing", "activation": "Grief that has become structural — no longer acute pain but the shape of the life built around the absence."},
            {"primitive_id": "melancholic-tendency", "activation": "The baseline sadness that grief leaves behind. Not depression — a permanent minor key that colors all experience."},
            {"primitive_id": "connection-seeking", "activation": "The need to connect persists, but every new connection is measured against the one that was lost. No one quite fits the empty chair."},
            {"primitive_id": "isolation-as-protection", "activation": "If you let someone in, they might die too. Distance is the only guarantee against repetition of the worst loss."},
            {"primitive_id": "capacity-for-change", "activation": "Can you change when changing means leaving the dead behind? Growth feels like betrayal when the grief is the last tether."},
        ],
        "shadow_activators": ["fragmentation", "guilt-conscience", "resistance-to-change"],
        "intensity": "moderate",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["loss-of-kin", "the-return"],
        "tension_situations": ["forced-role-change"],
    },
    "impossible-command": {
        "name": "Impossible Command",
        "category": "power-dynamics",
        "essence": "Every available option violates some binding rule — obedience and disobedience are both transgressions",
        "psychological_pressure": "The trap is structural, not moral. You're not choosing between good and bad — you're choosing between two forms of disobedience. Whatever you do, you've broken a rule. The system itself is the problem, and you're inside it.",
        "shadow_trigger": "Malicious compliance — obeying the letter so precisely that the absurdity becomes everyone's problem. Or total breakdown — the mind that can't resolve the contradiction simply stops functioning.",
        "observable_markers": [
            "Paralysis at the point of decision",
            "Increasingly creative attempts to find a third option that doesn't exist",
            "The authority issuing the command unaware of — or indifferent to — its impossibility",
        ],
        "pressure_targets": [
            {"primitive_id": "rigid-adherence", "activation": "The rule-follower faces their nightmare: the rules contradict each other. Adherence to one requires violation of another."},
            {"primitive_id": "adaptive-flexibility", "activation": "The creative mind searches for the third path — the loophole, the reframe, the Gordian solution. Sometimes it exists. Sometimes it doesn't."},
            {"primitive_id": "defiance-rebellion", "activation": "Refuse the premise. If the command is impossible, the commander is wrong. But refusing may cost more than choosing."},
            {"primitive_id": "methodical-approach", "activation": "Step by step through the logic: if A then not-B, if B then not-A. The method reveals the trap but doesn't escape it."},
            {"primitive_id": "stoic-acceptance", "activation": "Accept the no-win. Choose the lesser violation, bear the consequences, and don't pretend it was clean."},
        ],
        "shadow_activators": ["fragmentation", "wrath", "resistance-to-change"],
        "intensity": "extreme",
        "escalation_pattern": "acute",
        "complementary_situations": ["coerced-compliance", "means-vs-ends", "loyalty-vs-truth"],
        "tension_situations": ["authority-under-question"],
    },
    "individual-vs-collective": {
        "name": "Individual vs. Collective",
        "category": "moral-dilemma",
        "essence": "One person's need, right, or desire conflicts with what's best for the group",
        "psychological_pressure": "Am I selfish for wanting what I want? Is the group tyrannical for demanding my surrender? Both framings are available, and neither is entirely wrong.",
        "shadow_trigger": "The collective becomes a mob that consumes individuals. The individual becomes a narcissist who mistakes selfishness for principle.",
        "observable_markers": [
            "Arguments framed as 'the needs of the many' vs. 'every person matters'",
            "Someone asked to sacrifice for a group that may not reciprocate",
            "Group pressure to conform or surrender individual priorities",
        ],
        "pressure_targets": [
            {"primitive_id": "personal-freedom-priority", "activation": "Autonomy is directly threatened. The group demands what you would not freely give."},
            {"primitive_id": "duty-over-desire", "activation": "Duty says serve the group. Desire says protect yourself. The primitive is split against itself."},
            {"primitive_id": "belonging-seeking", "activation": "Resisting the group risks exclusion. Compliance preserves belonging but costs authenticity."},
            {"primitive_id": "justice-seeking", "activation": "Is it just to sacrifice one for many? Is it just to privilege one over all?"},
            {"primitive_id": "defiance-rebellion", "activation": "Resistance to collective pressure becomes heroism or selfishness depending on the frame."},
        ],
        "shadow_activators": ["pride", "guilt-conscience", "wrath"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["sacrifice-demanded", "resource-scarcity"],
        "tension_situations": ["coerced-compliance"],
    },
    "information-asymmetry": {
        "name": "Information Asymmetry",
        "category": "resource-pressure",
        "essence": "Some know critical things others don't — knowledge itself is the contested resource",
        "psychological_pressure": "Not knowing is vulnerability. Knowing and withholding is power. The asymmetry corrupts both sides — the ignorant become paranoid, the informed become manipulative.",
        "shadow_trigger": "Knowledge becomes hoarding. Sharing becomes calculated. Every conversation becomes an intelligence operation.",
        "observable_markers": [
            "One party making decisions the other can't understand or predict",
            "Trust substituting for knowledge — 'just trust me' replaces evidence",
            "The informed party choosing what to reveal and when",
        ],
        "pressure_targets": [
            {"primitive_id": "strategic-deception", "activation": "The temptation to control information flow is enormous. What you know and when you share it becomes your primary tool."},
            {"primitive_id": "truth-above-all", "activation": "Withholding information feels like lying by omission. Truth-seekers are torn between transparency and strategy."},
            {"primitive_id": "anxious-vigilance", "activation": "Not knowing what others know triggers constant scanning for clues and hidden meanings."},
            {"primitive_id": "curiosity-driven-exploration", "activation": "The gap in knowledge becomes an itch. Must find out what's being hidden."},
            {"primitive_id": "patient-observation", "activation": "Watching for what the informed party reveals through behavior, tone, and omission."},
        ],
        "shadow_activators": ["pride", "fragmentation"],
        "intensity": "moderate",
        "escalation_pattern": "building",
        "complementary_situations": ["power-imbalance", "betrayal-discovery"],
        "tension_situations": ["exposed-secret"],
    },
    "into-the-wild": {
        "name": "Into the Wild",
        "category": "resource-pressure",
        "essence": "Alone in nature without civilization's scaffolding — what survives when everything human is stripped away",
        "psychological_pressure": "Civilization is a contract — you give up wildness for safety. The wilderness revokes that contract. Every skill you have is suddenly irrelevant except the most basic: keep breathing.",
        "shadow_trigger": "The wild self takes over and the social self atrophies. Return to civilization becomes impossible — not because you can't, but because you no longer fit.",
        "observable_markers": [
            "Attention shifts entirely to immediate physical needs — water, shelter, fire",
            "Time loses social meaning — days measured by sunlight, not clocks",
            "Talking to oneself or to the wilderness as a way of maintaining sanity",
        ],
        "pressure_targets": [
            {"primitive_id": "survival-instinct", "activation": "Survival becomes the only priority. The animal brain takes over — food, water, warmth, shelter. Everything else is luxury."},
            {"primitive_id": "adaptive-flexibility", "activation": "Rigid plans fail in wilderness. You must adapt to terrain, weather, and the land's indifference to your intentions."},
            {"primitive_id": "patient-observation", "activation": "Nature rewards those who watch and wait. The impatient starve. Reading the landscape becomes a survival skill."},
            {"primitive_id": "isolation-as-protection", "activation": "Solitude is not chosen — it is imposed. But the wilderness teaches that aloneness has its own terrible clarity."},
            {"primitive_id": "stoic-acceptance", "activation": "The wild does not negotiate. Rain falls. Rivers flood. Animals hunt. Acceptance of what cannot be changed is the first lesson."},
        ],
        "shadow_activators": ["fragmentation", "wrath", "resistance-to-change"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["resource-scarcity", "exile-banishment"],
        "tension_situations": ["contested-resource"],
    },
    "loss-of-kin": {
        "name": "Loss of Kin",
        "category": "relational-tension",
        "essence": "The people who defined you are dead — not betrayal, not choice, just gone",
        "psychological_pressure": "Family is the first mirror — the people who told you who you were before you could decide for yourself. When they're gone, the mirror shatters. You still exist, but the reflection that confirmed you is lost.",
        "shadow_trigger": "The grief becomes a fortress. No new bond can replace what was lost, so no new bond is permitted. The dead become more real than the living.",
        "observable_markers": [
            "Talking about the dead in present tense or catching themselves doing it",
            "Carrying an heirloom or memento that has become almost sacred",
            "Flinching at casual mentions of family by others",
        ],
        "pressure_targets": [
            {"primitive_id": "grief-processing", "activation": "The primary pressure — metabolizing the loss of the people who were the foundation of identity."},
            {"primitive_id": "connection-seeking", "activation": "The need for belonging doesn't die with the family — it becomes a wound that aches for what can never return."},
            {"primitive_id": "rage-response", "activation": "If the deaths were caused — by raiders, war, plague that could have been stopped — grief curdles into fury."},
            {"primitive_id": "isolation-as-protection", "activation": "Everyone I love dies. The logical response is to love no one. Withdrawal becomes prophylaxis against future loss."},
            {"primitive_id": "inherited-identity", "activation": "With the family gone, the inherited identity has no living anchor. Who carries the name now? Only you — and the weight is crushing."},
        ],
        "shadow_activators": ["wrath", "fragmentation", "guilt-conscience"],
        "intensity": "extreme",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["griefs-long-shadow", "exile-banishment"],
        "tension_situations": ["forced-alliance"],
    },
    "loyalty-vs-truth": {
        "name": "Loyalty vs. Truth",
        "category": "moral-dilemma",
        "essence": "Honesty will harm someone you care about — silence protects them but betrays your principles",
        "psychological_pressure": "Two things you value cannot coexist in this moment. Telling the truth makes you a betrayer. Keeping the secret makes you a liar. There is no clean option.",
        "shadow_trigger": "Loyalty becomes enabling — protecting someone from consequences they've earned. Truth becomes cruelty — using honesty as a weapon to salve your own conscience.",
        "observable_markers": [
            "Someone holds information that could protect the group but damage an ally",
            "Conversations become careful, hedged, full of omissions",
            "The truthful option and the loyal option point in opposite directions",
        ],
        "pressure_targets": [
            {"primitive_id": "truth-above-all", "activation": "Your core value says speak. Your heart says don't. The truth is a bomb with a friend standing on it."},
            {"primitive_id": "loyal-companionship", "activation": "Loyalty is tested at its limit — does loyalty mean protecting someone from truth, or respecting them enough to share it?"},
            {"primitive_id": "strategic-deception", "activation": "Partial truths, selective disclosure, and careful framing become tempting middle paths."},
            {"primitive_id": "guilt-conscience", "activation": "Either choice generates guilt. Speak and betray; stay silent and enable."},
            {"primitive_id": "harmony-over-conflict", "activation": "The peacemaker wants a path that preserves both relationships. There may not be one."},
        ],
        "shadow_activators": ["guilt-conscience", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "acute",
        "complementary_situations": ["information-asymmetry", "exposed-secret"],
        "tension_situations": ["means-vs-ends"],
    },
    "means-vs-ends": {
        "name": "Means vs. Ends",
        "category": "moral-dilemma",
        "essence": "The right outcome requires wrong methods — or the right methods produce a terrible outcome",
        "psychological_pressure": "You can do the right thing and fail, or the wrong thing and succeed. The world doesn't care about your moral purity — it cares about outcomes. But you have to live with yourself.",
        "shadow_trigger": "Consequentialism without conscience — anything is justified if it works. Or paralytic moralism — nothing is done because nothing can be done purely.",
        "observable_markers": [
            "Someone arguing that the goal justifies the cost",
            "Clean hands vs. dirty hands — purity vs. effectiveness",
            "Retrospective justification: 'it worked, so it was right'",
        ],
        "pressure_targets": [
            {"primitive_id": "justice-seeking", "activation": "Justice demands the right outcome. But what if the path to justice requires injustice?"},
            {"primitive_id": "strategic-deception", "activation": "Deception might be the only effective tool. Does the cause sanctify the method?"},
            {"primitive_id": "guilt-conscience", "activation": "Whatever you choose, the other option haunts. Success through wrong methods still stains."},
            {"primitive_id": "methodical-approach", "activation": "Step-by-step reasoning must confront the gap between process and outcome."},
            {"primitive_id": "truth-above-all", "activation": "If the truth is that dirty methods work better, does truth demand using them?"},
        ],
        "shadow_activators": ["guilt-conscience", "pride", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "acute",
        "complementary_situations": ["loyalty-vs-truth", "coerced-compliance"],
        "tension_situations": ["individual-vs-collective"],
    },
    "power-imbalance": {
        "name": "Power Imbalance",
        "category": "power-dynamics",
        "essence": "One party has structural advantage — the stakes are asymmetric and so is the risk",
        "psychological_pressure": "The less powerful must calculate every word. The more powerful may not even notice the imbalance. The gap in awareness is itself a form of power.",
        "shadow_trigger": "The powerful become blind to their advantage and punish those who point it out. The powerless become servile or secretly plotting.",
        "observable_markers": [
            "One party can impose consequences the other cannot",
            "Deference, caution, or performance from the less powerful",
            "The powerful party treating their advantage as natural or earned",
        ],
        "pressure_targets": [
            {"primitive_id": "defiance-rebellion", "activation": "Resistance is dangerous but may be necessary. The cost of speaking up falls entirely on the weaker party."},
            {"primitive_id": "strategic-deception", "activation": "The less powerful learn to perform compliance while preserving inner autonomy. Masks become survival tools."},
            {"primitive_id": "anxious-vigilance", "activation": "The less powerful must read every cue from the powerful — tone, mood, whim — because their safety depends on it."},
            {"primitive_id": "stoic-acceptance", "activation": "Endurance without complaint may be the only viable strategy. But acceptance can slide into complicity."},
            {"primitive_id": "justice-seeking", "activation": "The imbalance itself may be unjust. But fighting it from below is costly and uncertain."},
        ],
        "shadow_activators": ["wrath", "pride", "envy"],
        "intensity": "moderate",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["coerced-compliance", "information-asymmetry", "authority-under-question"],
        "tension_situations": ["forced-alliance"],
    },
    "prolonged-uncertainty": {
        "name": "Prolonged Uncertainty",
        "category": "temporal-pressure",
        "essence": "No resolution is coming — the situation will remain ambiguous indefinitely",
        "psychological_pressure": "Humans are wired to resolve uncertainty. When resolution is impossible, the mind generates its own — superstition, conspiracy, false certainty. Anything is better than not knowing.",
        "shadow_trigger": "Manufactured certainty. People adopt rigid positions not because they're right but because ambiguity is unbearable. False prophets gain followers because certainty feels like relief.",
        "observable_markers": [
            "People oscillating between hope and despair without new information",
            "Rituals of waiting — checking, rechecking, interpreting signs",
            "Frustration directed at those who promise answers",
        ],
        "pressure_targets": [
            {"primitive_id": "patient-observation", "activation": "Patience is tested at its absolute limit. Observation without resolution becomes a practice of endurance."},
            {"primitive_id": "anxious-vigilance", "activation": "Vigilance with no resolution becomes chronic anxiety. The sentinel never stands down because the threat never resolves."},
            {"primitive_id": "impulsive-action", "activation": "The urge to DO something — anything — to break the stalemate. Action as relief from waiting."},
            {"primitive_id": "stoic-acceptance", "activation": "Accepting what cannot be changed is the stoic ideal. But acceptance of permanent uncertainty feels like surrender."},
            {"primitive_id": "philosophical-contemplation", "activation": "The mind turns to meaning-making. If the situation won't resolve, perhaps it can be understood."},
        ],
        "shadow_activators": ["fragmentation", "resistance-to-change", "envy"],
        "intensity": "moderate",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["information-asymmetry", "power-imbalance"],
        "tension_situations": ["countdown-crisis"],
    },
    "reputation-under-attack": {
        "name": "Reputation Under Attack",
        "category": "identity-threat",
        "essence": "What others believe about you is being damaged — the social self is under assault",
        "psychological_pressure": "Reputation is the self that others carry. When it's attacked, you're fighting on a battlefield you can't fully see — inside other people's minds. Defending yourself can look guilty. Silence can look like admission.",
        "shadow_trigger": "Obsessive reputation management — every action filtered through 'how does this look?' Identity collapses into performance.",
        "observable_markers": [
            "Accusations, rumors, or misrepresentations circulating",
            "People who knew you now looking at you differently",
            "The attacked person choosing between dignified silence and vigorous defense",
        ],
        "pressure_targets": [
            {"primitive_id": "pride", "activation": "Self-image is directly under fire. Pride demands defense, but vigorous defense can backfire."},
            {"primitive_id": "defiance-rebellion", "activation": "The instinct to fight back, to refuse the false narrative, to burn down anyone who slanders you."},
            {"primitive_id": "stoic-acceptance", "activation": "The Stoic position: reputation is externals, beyond your control. But few can truly release it."},
            {"primitive_id": "truth-above-all", "activation": "If the attack is false, truth should be sufficient defense. If truth is insufficient, what does that say about truth's power?"},
            {"primitive_id": "humility", "activation": "Can you let go of what others think? Or is some reputation necessary for functioning in the world?"},
        ],
        "shadow_activators": ["pride", "wrath", "envy"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["exposed-secret", "information-asymmetry"],
        "tension_situations": ["forced-role-change"],
    },
    "resource-scarcity": {
        "name": "Resource Scarcity",
        "category": "resource-pressure",
        "essence": "Not enough to go around — survival or well-being depends on allocation decisions",
        "psychological_pressure": "Scarcity strips away abstraction. Philosophy gives way to arithmetic. Who gets what, and who decides? Every generous impulse now carries a survival cost.",
        "shadow_trigger": "Selfishness masquerading as pragmatism. Hoarding justified as preparation. Generosity weaponized as moral superiority over those who ration.",
        "observable_markers": [
            "Rationing, hoarding, or guarding of supplies",
            "Conversations shift from goals to survival",
            "Alliances form and break around access to what's scarce",
        ],
        "pressure_targets": [
            {"primitive_id": "generosity", "activation": "Generosity becomes costly — giving means going without. Tests whether generosity survives when it hurts."},
            {"primitive_id": "justice-seeking", "activation": "Who deserves what? Fairness is easy in abundance; scarcity forces hard choices about distribution."},
            {"primitive_id": "strategic-deception", "activation": "Information about remaining resources becomes power. Incentive to hide, misrepresent, or hoard secretly."},
            {"primitive_id": "duty-over-desire", "activation": "Personal need conflicts with obligation to share or protect the group."},
            {"primitive_id": "anxious-vigilance", "activation": "Threat becomes concrete and constant. Vigilance shifts from personality trait to survival necessity."},
        ],
        "shadow_activators": ["envy", "pride", "wrath"],
        "intensity": "moderate",
        "escalation_pattern": "building",
        "complementary_situations": ["contested-resource", "countdown-crisis", "power-imbalance"],
        "tension_situations": ["abundance-asymmetry"],
    },
    "sacred-guardianship": {
        "name": "Sacred Guardianship",
        "category": "moral-dilemma",
        "essence": "You hold something powerful, dangerous, or precious — and it tempts you even as you protect it",
        "psychological_pressure": "The thing you protect also tests you. Proximity to power is itself corrupting. The guardian must resist not only external threats but the internal whisper: use it. You could use it well. You deserve to use it.",
        "shadow_trigger": "The guardian becomes the dragon — hoarding what they were meant to protect, unable to distinguish stewardship from ownership. 'No one else can be trusted with it' becomes 'it's mine.'",
        "observable_markers": [
            "The guardian increasingly isolated by the burden",
            "Others wanting the guarded thing — for good reasons or bad",
            "The guardian's relationship with the guarded thing becoming intimate, possessive, or corrosive",
        ],
        "pressure_targets": [
            {"primitive_id": "self-mastery", "activation": "The central demand — discipline against temptation. The thing you guard offers power, knowledge, or relief, and you must refuse it daily."},
            {"primitive_id": "duty-over-desire", "activation": "Duty says protect. Desire says use. The guardian's entire existence is this tension."},
            {"primitive_id": "obsessive-focus", "activation": "The guarded thing becomes the center of life. Everything else falls away. Vigilance becomes obsession."},
            {"primitive_id": "isolation-as-protection", "activation": "The guardian withdraws — partly to protect the thing, partly because the burden makes normal life impossible."},
            {"primitive_id": "stoic-acceptance", "activation": "Bearing the weight without complaint. The guardian role is thankless — others don't know what you carry, and you can't tell them."},
        ],
        "shadow_activators": ["pride", "wrath", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["forbidden-knowledge", "individual-vs-collective", "resource-scarcity"],
        "tension_situations": ["contested-resource"],
    },
    "sacrifice-demanded": {
        "name": "Sacrifice Demanded",
        "category": "relational-tension",
        "essence": "You must give up something precious for someone else — the cost falls on you alone",
        "psychological_pressure": "Sacrifice given freely is nobility. Sacrifice demanded is extraction. The difference is consent — but the cost is identical. The question is whether what's lost was yours to keep.",
        "shadow_trigger": "Martyrdom as identity — the sacrifice becomes the person's defining quality, and they use it as permanent moral leverage. Or refusal to sacrifice becoming permanent selfishness.",
        "observable_markers": [
            "Calculation of what's being asked vs. what's being offered",
            "The person demanding sacrifice presenting it as natural or necessary",
            "Resentment building even when the sacrifice is willing",
        ],
        "pressure_targets": [
            {"primitive_id": "generosity", "activation": "Generosity is tested at its most expensive. Giving when it costs nothing is easy. Giving when it costs everything is the real test."},
            {"primitive_id": "duty-over-desire", "activation": "Duty says give. Desire says keep. The primitive is purpose-built for this collision."},
            {"primitive_id": "self-mastery", "activation": "Can you choose the sacrifice deliberately, or does the demand override your agency?"},
            {"primitive_id": "personal-freedom-priority", "activation": "What's being sacrificed may be freedom itself — autonomy surrendered for another's benefit."},
            {"primitive_id": "rage-response", "activation": "Even willing sacrifice generates resentment when the beneficiary doesn't acknowledge the cost. Suppressed anger at being the one who pays."},
        ],
        "shadow_activators": ["guilt-conscience", "pride", "wrath"],
        "intensity": "high",
        "escalation_pattern": "acute",
        "complementary_situations": ["individual-vs-collective", "resource-scarcity"],
        "tension_situations": ["contested-resource"],
    },
    "spreading-corruption": {
        "name": "Spreading Corruption",
        "category": "resource-pressure",
        "essence": "Something is spreading — disease, suspicion, moral decay, influence — and it transforms what it touches",
        "psychological_pressure": "Corruption spreads invisibly. By the time you see it, it's already past the boundary. Trust becomes impossible because the corrupted look the same as the clean — until they don't. The question shifts from 'how do we fix this?' to 'who can we still trust?'",
        "shadow_trigger": "Paranoia. Everyone is suspect. The fear of corruption becomes more destructive than the corruption itself. Witch hunts, purges, loyalty tests — the cure is worse than the disease because the cure requires someone to decide who's clean.",
        "observable_markers": [
            "Healthy systems beginning to malfunction in the same way",
            "Accusations of contamination — who's been affected, who's still clean",
            "Quarantine behaviour — cutting off the affected, isolating the unaffected",
        ],
        "pressure_targets": [
            {"primitive_id": "anxious-vigilance", "activation": "Threat that's invisible and spreading validates every paranoid instinct. The sentinel cannot stand down because the danger is everywhere and nowhere."},
            {"primitive_id": "patient-observation", "activation": "Watching for signs of the spread. Who's been affected? Who's acting differently? Observation becomes surveillance."},
            {"primitive_id": "isolation-as-protection", "activation": "Quarantine — of self, of others, of ideas. If connection is the vector, isolation is the defence. But isolation also kills."},
            {"primitive_id": "justice-seeking", "activation": "Who is responsible? Who started it? Who let it spread? Justice-seeking under contagion becomes the search for a source — which easily becomes the search for a scapegoat."},
            {"primitive_id": "strategic-deception", "activation": "Hiding symptoms. If the corrupted are punished or quarantined, the incentive is to conceal. Every act of concealment accelerates the spread."},
        ],
        "shadow_activators": ["fragmentation", "wrath", "envy"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["resource-scarcity", "information-asymmetry", "betrayal-discovery"],
        "tension_situations": ["the-outsider-arrives"],
    },
    "succession-crisis": {
        "name": "Succession Crisis",
        "category": "power-dynamics",
        "essence": "Power is transferring — the current holder is weakening, and the question of who comes next splits everything apart",
        "psychological_pressure": "Succession is a controlled explosion. The old order is ending — everyone knows it — but the new order isn't determined. The interregnum is where the real violence happens, because everything is possible and nothing is stable.",
        "shadow_trigger": "The heirs destroy what they're trying to inherit. Competition for the legacy consumes the legacy itself. Lear's kingdom divided is Lear's kingdom destroyed.",
        "observable_markers": [
            "Potential successors positioning, allying, undermining",
            "The current holder either clinging or abdicating too fast",
            "Loyalties shifting as the power calculus changes",
        ],
        "pressure_targets": [
            {"primitive_id": "charismatic-leadership", "activation": "The successor must inspire confidence before they have power. Leadership here is prospective — you lead by promising what you'll be, not by being it."},
            {"primitive_id": "pride", "activation": "For the departing leader: releasing power gracefully. For heirs: whether the pursuit of succession is ambition or duty."},
            {"primitive_id": "duty-over-desire", "activation": "Is succession about serving the institution or serving yourself? The best answer is both. The honest answer is complicated."},
            {"primitive_id": "patient-observation", "activation": "The wisest heir may be the one watching rather than maneuvering. But patience can look like weakness."},
            {"primitive_id": "strategic-deception", "activation": "Alliances form and break. Promises are made. The succession game rewards those who control perception — who seems ready, loyal, strong."},
        ],
        "shadow_activators": ["pride", "envy", "wrath"],
        "intensity": "high",
        "escalation_pattern": "building",
        "complementary_situations": ["authority-under-question", "contested-resource", "power-imbalance"],
        "tension_situations": ["forced-alliance"],
    },
    "the-apprenticeship": {
        "name": "The Apprenticeship",
        "category": "relational-tension",
        "essence": "You learned everything from one person — now you must decide what of their teaching to keep and what to reject",
        "psychological_pressure": "The teacher made you. Every skill, every insight, every instinct was shaped by their hands. To reject their teaching feels like self-amputation. To follow it blindly means never becoming yourself.",
        "shadow_trigger": "Parricide of the mentor — the student must symbolically kill the teacher to become themselves. Or permanent subordination — the eternal student who never claims their own authority.",
        "observable_markers": [
            "Unconsciously mimicking the teacher's gestures, phrases, or methods",
            "Growing tension between gratitude for the teaching and frustration with its limits",
            "The moment of surpassing — the student realizes they have exceeded the mentor",
        ],
        "pressure_targets": [
            {"primitive_id": "humility", "activation": "The student must remain humble enough to learn — but not so humble that they never challenge what they've been taught."},
            {"primitive_id": "capacity-for-change", "activation": "Growing beyond the mentor requires changing the foundation they built. The student must become something the teacher didn't intend."},
            {"primitive_id": "duty-over-desire", "activation": "Obligation to the teacher — repayment of the teaching debt. Does duty mean obedience or does duty mean becoming the best version, even if the mentor disapproves?"},
            {"primitive_id": "patient-observation", "activation": "The apprentice learns by watching. The accumulated observation eventually reveals the teacher's flaws — the cracks in the foundation."},
            {"primitive_id": "pride", "activation": "The pride of surpassing — realizing you have outgrown your teacher. And the guilt that accompanies it, because the growth feels like betrayal."},
        ],
        "shadow_activators": ["pride", "guilt-conscience", "resistance-to-change"],
        "intensity": "moderate",
        "escalation_pattern": "building",
        "complementary_situations": ["authority-under-question", "forced-role-change"],
        "tension_situations": ["betrayal-discovery"],
    },
    "the-criminal-past": {
        "name": "The Criminal Past",
        "category": "moral-dilemma",
        "essence": "You lived outside the law — not by accident but by choice or necessity. The question now is whether the person who did those things is still you",
        "psychological_pressure": "Redemption requires believing you can change. But the skills, the instincts, the muscle memory — they don't care about your moral progress. You can choose to be good. The question is whether the world will let you.",
        "shadow_trigger": "The past becomes an excuse. 'I was born bad' is easier than the daily work of choosing differently. Or the past becomes a secret that poisons every honest relationship.",
        "observable_markers": [
            "Instinctive caution — checking exits, reading crowds, sleeping light",
            "Skills that serve honest life but betray their origin (lockpicking, deception, threat assessment)",
            "Flinching when someone from the old life appears or when a familiar pattern emerges",
        ],
        "pressure_targets": [
            {"primitive_id": "guilt-conscience", "activation": "The weight of what was done. Guilt that doesn't fade because the victims don't un-suffer. Conscience that arrived too late to prevent the harm."},
            {"primitive_id": "strategic-deception", "activation": "The old skills are still there — lying, manipulating, reading people. Using them for good doesn't change their origin. Every honest moment is built on a foundation of learned deception."},
            {"primitive_id": "defiance-rebellion", "activation": "The original defiance that led to crime — against unjust systems, against poverty, against a world that offered no legitimate path. Was it wrong? It was illegal. Those aren't the same thing."},
            {"primitive_id": "risk-taking", "activation": "The appetite for risk doesn't disappear with reform. The thrill of the score, the edge of danger — sobriety from crime is as hard as sobriety from any addiction."},
            {"primitive_id": "capacity-for-change", "activation": "Can people truly change? The criminal past is the ultimate test of this primitive. Every day is a choice, and the old life is always one decision away."},
        ],
        "shadow_activators": ["guilt-conscience", "pride", "wrath"],
        "intensity": "high",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["exposed-secret", "reputation-under-attack"],
        "tension_situations": ["sacred-guardianship"],
    },
    "the-curse": {
        "name": "The Curse",
        "category": "identity-threat",
        "essence": "Something has been done to you that is changing what you are — the body or soul as territory under occupation",
        "psychological_pressure": "The curse is not an enemy you can fight — it is you, becoming something else. The horror is not external; it is the slow realization that the thing you fear is already inside. At what point do you stop being you?",
        "shadow_trigger": "Surrender to the curse — embracing the transformation because fighting it is exhausting. The monster was always easier than the man.",
        "observable_markers": [
            "Physical or behavioral changes that the character cannot fully control",
            "Increasing isolation as the curse becomes harder to hide",
            "Desperate research or questing for a cure — or gradual acceptance",
        ],
        "pressure_targets": [
            {"primitive_id": "resistance-to-change", "activation": "The most literal activation — resisting change that is happening to the body or soul. Holding onto the self while the self is being rewritten."},
            {"primitive_id": "capacity-for-change", "activation": "The dark mirror of growth — change imposed rather than chosen. Can you find agency in transformation you didn't consent to?"},
            {"primitive_id": "isolation-as-protection", "activation": "Withdrawal not from fear but from mercy — you isolate to protect others from what you're becoming."},
            {"primitive_id": "self-mastery", "activation": "Can you master what you're becoming? The curse tests discipline at its most extreme — controlling urges that didn't exist before the transformation began."},
            {"primitive_id": "survival-instinct", "activation": "The will to survive even when survival means continuing as something monstrous. Is a cursed life still worth living?"},
        ],
        "shadow_activators": ["fragmentation", "wrath", "pride"],
        "intensity": "extreme",
        "escalation_pattern": "building",
        "complementary_situations": ["the-ordeal", "exile-banishment"],
        "tension_situations": ["the-return"],
    },
    "the-ordeal": {
        "name": "The Ordeal",
        "category": "identity-threat",
        "essence": "A trial that will prove or transform who you are — you enter one person and emerge another, or not at all",
        "psychological_pressure": "The ordeal is not just about success or failure — it's about revelation. Under extreme pressure, the masks come off. What remains when everything comfortable is stripped away is who you actually are. That truth may be better or worse than what you believed.",
        "shadow_trigger": "Proving yourself becomes the only thing that matters. The ordeal is passed but the testing never stops — every situation becomes another trial, another chance to prove, another opportunity to fail. Rest becomes impossible.",
        "observable_markers": [
            "Preparation rituals, both practical and psychological",
            "The tested person drawing on reserves they didn't know they had",
            "Witnesses or judges evaluating the performance",
        ],
        "pressure_targets": [
            {"primitive_id": "self-mastery", "activation": "Discipline under fire. The ordeal demands everything you've trained for — and then asks for more."},
            {"primitive_id": "risk-taking", "activation": "The trial requires committing fully. Half-measures fail ordeals. You must risk everything to pass."},
            {"primitive_id": "obsessive-focus", "activation": "The ordeal narrows the world to a single point. Everything irrelevant falls away. What remains is purpose."},
            {"primitive_id": "capacity-for-change", "activation": "The purpose of many ordeals is transformation. The person who enters is supposed to die so the new person can be born. Whether you permit that death is the real test."},
            {"primitive_id": "pride", "activation": "The desire to prove yourself — to yourself and to watchers. Pride as fuel. But pride as fuel burns out, and what's left?"},
        ],
        "shadow_activators": ["pride", "wrath", "fragmentation"],
        "intensity": "extreme",
        "escalation_pattern": "acute",
        "complementary_situations": ["countdown-crisis", "forced-role-change", "sacrifice-demanded"],
        "tension_situations": ["prolonged-uncertainty"],
    },
    "the-outsider-arrives": {
        "name": "The Outsider Arrives",
        "category": "relational-tension",
        "essence": "A stranger enters an established community — and by their mere presence, everything begins to shift",
        "psychological_pressure": "The outsider reveals what was hidden. Tensions the community suppressed become visible because the outsider doesn't know the rules. Bonds the community assumed were strong are tested by a new variable. The stranger is a mirror, and the community may not like what it sees.",
        "shadow_trigger": "Scapegoating. The community blames the outsider for problems that existed before they arrived. Or seduction — the outsider is idealized, and everything local is devalued by comparison.",
        "observable_markers": [
            "The community tightening ranks, performing unity that may not have existed before",
            "Curiosity and suspicion coexisting in every interaction with the newcomer",
            "The outsider catalyzing conflicts that predated their arrival",
        ],
        "pressure_targets": [
            {"primitive_id": "cautious-conservatism", "activation": "The community's immune response — protect what exists, resist the new, close ranks around the familiar."},
            {"primitive_id": "curiosity-driven-exploration", "activation": "But the stranger brings something new. Stories, skills, perspectives. The curious are drawn toward what they don't understand."},
            {"primitive_id": "connection-seeking", "activation": "The outsider needs to belong. Every interaction is audition, negotiation, performance. Belonging must be earned in a currency they may not have."},
            {"primitive_id": "anxious-vigilance", "activation": "Watchfulness on both sides. The community watches the stranger for threat. The stranger watches the community for acceptance."},
            {"primitive_id": "social-wit", "activation": "Navigating unfamiliar social codes. The outsider must read a room they've never been in, with rules no one explains."},
        ],
        "shadow_activators": ["pride", "envy", "wrath"],
        "intensity": "moderate",
        "escalation_pattern": "building",
        "complementary_situations": ["exile-banishment", "power-imbalance", "reputation-under-attack"],
        "tension_situations": ["forced-alliance"],
    },
    "the-return": {
        "name": "The Return",
        "category": "identity-threat",
        "essence": "You come back to where you started — but you've changed, and so has everything else",
        "psychological_pressure": "Home was supposed to be the destination. You endured everything for the promise of return. But the return reveals that home was a memory, and the person who left doesn't exist anymore. You can't go back because 'back' is gone.",
        "shadow_trigger": "Nostalgia as delusion — insisting that nothing has changed when everything has. Or contempt for home — the returned traveler finding everything smaller, slower, less than what they've seen.",
        "observable_markers": [
            "Familiar places feeling alien, or alien places suddenly familiar",
            "Others expecting the person who left, not the person who returned",
            "The returner performing their old self while their new self watches",
        ],
        "pressure_targets": [
            {"primitive_id": "capacity-for-change", "activation": "The return tests whether transformation is real. Did you actually change, or did you just adapt temporarily? Home is the mirror."},
            {"primitive_id": "belonging-seeking", "activation": "The whole journey was about getting back. But belonging requires fitting, and you no longer fit the shape you left."},
            {"primitive_id": "isolation-as-protection", "activation": "The gap between who you are and who they remember creates distance. Easier to withdraw than to explain what happened."},
            {"primitive_id": "patient-observation", "activation": "Odysseus in disguise — watching before revealing. The wise returner observes how things have changed before declaring they're home."},
            {"primitive_id": "melancholic-tendency", "activation": "Grief for the home that was. The return was supposed to end the sadness. Instead, it reveals a new kind of loss."},
        ],
        "shadow_activators": ["pride", "fragmentation", "envy"],
        "intensity": "moderate",
        "escalation_pattern": "slow-burn",
        "complementary_situations": ["forced-role-change", "prolonged-uncertainty", "exposed-secret"],
        "tension_situations": ["exile-banishment"],
    },
    "witness-to-wrongdoing": {
        "name": "Witness to Wrongdoing",
        "category": "moral-dilemma",
        "essence": "You see something wrong happening — and must choose between intervention and self-preservation",
        "psychological_pressure": "Seeing is not neutral. Once you've witnessed, you're implicated — silence is a choice, and it's the choice that protects you. Speaking up costs. Not speaking up corrodes. There is no position of innocent observer.",
        "shadow_trigger": "Learned helplessness disguised as pragmatism. 'What could I have done?' becomes a permanent excuse. Or reckless intervention that makes everything worse — heroism as ego.",
        "observable_markers": [
            "The witness freezing, calculating, rationalizing delay",
            "Others present also not acting — the diffusion of responsibility",
            "The wrong continuing because no one breaks the silence",
        ],
        "pressure_targets": [
            {"primitive_id": "justice-seeking", "activation": "This is wrong. You know it's wrong. Justice demands action. But action demands courage, and courage demands risk."},
            {"primitive_id": "anxious-vigilance", "activation": "Hyperawareness of the danger — both the wrong being committed and the danger of intervening. The witness sees everything and is paralyzed by the seeing."},
            {"primitive_id": "harmony-over-conflict", "activation": "The peacemaker wants to believe it's not that bad, that someone else will handle it, that intervention will cause more harm. Every excuse available."},
            {"primitive_id": "guilt-conscience", "activation": "Inaction generates guilt immediately. You watched. You could have acted. Whether you act later doesn't erase the moment you didn't."},
            {"primitive_id": "defiance-rebellion", "activation": "The rebel's instinct: intervene, damn the consequences. But rebellion against a wrong in progress is different from rebellion against a system — it's immediate and personal."},
        ],
        "shadow_activators": ["guilt-conscience", "wrath", "fragmentation"],
        "intensity": "high",
        "escalation_pattern": "acute",
        "complementary_situations": ["power-imbalance", "loyalty-vs-truth", "means-vs-ends"],
        "tension_situations": ["prolonged-uncertainty"],
    },
}


SITUATION_CATEGORIES = {
    "identity-threat": {"name": "Identity Threat", "count": 10},
    "moral-dilemma": {"name": "Moral Dilemma", "count": 8},
    "power-dynamics": {"name": "Power Dynamics", "count": 5},
    "relational-tension": {"name": "Relational Tension", "count": 8},
    "resource-pressure": {"name": "Resource Pressure", "count": 6},
    "temporal-pressure": {"name": "Temporal Pressure", "count": 2},
}
